# Generated by Django 3.1 on 2020-08-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
